buildpack: https://github.com/pkgr/pkgr-noop-buildpack#master
before_install: scripts/preinstall
after_install: scripts/postinstall
before_precompile: scripts/before_compile.sh
after_precompile: scripts/after_compile.sh
targets:
  debian-8:
  debian-9:
  debian-10:
  debian-11:
  ubuntu-16.04:
  ubuntu-18.04:
  ubuntu-20.04:
  ubuntu-22.04:
  centos-6:
  centos-7:
  centos-8:
  sles-12:
